
name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build -t shabimana1/mario .

      - name: Push image
        run: |
          docker login -u shabimana1 -p ${{secrets.REGISTRY_PASS}}
          docker push shabimana1/mario:v2
